---
- name: Отключить старый swap
  command: swapoff "{{ swap_file_path }}"

- name: Создать новый swap-файл
  command: dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_size }}
  args:
    creates: "{{ swap_file_path }}"

- name: Установить права для swapfile
  file:
    path: "{{ swap_file_path }}"
    mode: '0600'

- name: Создать swap на новом файле
  command: mkswap "{{ swap_file_path }}"

- name: Включить swap
  command: swapon "{{ swap_file_path }}"

- name: Показать информацию о swap
  command: swapon --show
