# roles/firewall/tasks/main.yml

---
- name: Setup firewall for Debian/Ubuntu
  when: "{{ is_debian_based }}"
  block:
    - name: Open common ports and deny traffic from BLOCK_ZONE_IP in UFW
      ufw:
        rule: "{{ item.rule }}"
        name: "{{ item.name }}"
        from_ip: "{{ item.from_ip }}"
        proto: "{{ item.proto }}"
        state: "{{ item.state }}"
      loop:
        - { rule: 'allow', name: "{{ item.name }}", proto: "{{ item.proto }}", state: 'enable' }
        - { rule: 'deny', from_ip: "{{ BLOCK_ZONE_PREFIX }}", proto: 'all', state: 'enable' }
      loop-control:
        loop_var: item

    - name: Enable UFW
      ufw:
        state: enable

- name: Setup firewall for CentOS/Fedora
  when: "{{ is_centos_based }}"
  block: 
    - name: Enable firewalld
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Allow ports in firewalld
      firewalld:
        port: "{{ item.name }}/tcp"
        permanent: yes
        state: enabled
      loop: "{{ common_ports }}"

    - name: Deny traffic from BLOCK_ZONE_IP
      firewalld:
        rich_rule: "rule family='ipv4' source address='{{ BLOCK_ZONE_PREFIX }}' reject"
        permanent: yes
        state: enabled

    - name: Reload firewalld
      firewalld:
        state: reloaded