---
- name: Check the operating system
  ansible.builtin.set_fact:
    is_debian_based: "{{ ansible_facts.os_family in ['Debian', 'Ubuntu'] }}"
    is_centos_based: "{{ ansible_facts.os_family in ['RedHat', 'CentOS', 'Fedora'] }}"

- name: Setup firewall for Debian/Ubuntu
  when: is_debian_based
  block:
    - name: Reset UFW rules
      ufw:
        state: reset

    - name: Allow port 36079/tcp
      ufw:
        rule: allow
        name: "36079"
        proto: tcp

    - name: Allow port 443/tcp
      ufw:
        rule: allow
        name: "443"
        proto: tcp

    - name: Deny traffic from BLOCK_ZONE_IP
      ufw:
        rule: deny
        from_ip: "{{ ansible_default_ipv4.address | ipaddr('prefix', 22) }}"
        proto: all

    - name: Enable UFW
      ufw:
        state: enabled

- name: Setup firewall for CentOS/Fedora
  when: is_centos_based
  block:
    - name: Enable firewalld
      systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Allow port 36079/tcp in firewalld
      firewalld:
        port: 36079/tcp
        permanent: yes
        state: enabled

    - name: Allow port 443/tcp in firewalld
      firewalld:
        port: 443/tcp
        permanent: yes
        state: enabled

    - name: Deny traffic from BLOCK_ZONE_IP in firewalld
      firewalld:
        rich_rule: "rule family='ipv4' source address='{{ ansible_default_ipv4.address | ipaddr('prefix', 22) }}' reject"
        permanent: yes
        state: enabled

    - name: Reload firewalld
      firewalld:
        state: reloaded
